a=int(input("예금액 입력 : "))
b=float(input("이자율 입력(%) : "))
print("-------------------------")
r=int(a*(b/100))
s=int(a+r)
print("예금액 : {}원".format(a))
print("이자율 : {}%".format(b))
print("예금이자 : {}원".format(r))
print("잔액 : {}원".format(s))
print("-------------------------")
r=format(r,",")
s=format(s,",")
print("예금액 : {}원".format(a))
print("이자율 : {}%".format(b))
print("예금이자 : {}원".format(r))
print("잔액 : {}원".format(s))
